import { readFileSync } from "node:fs";
import { exec } from "../lib/exec.js";
import {
  checkGhInstalled,
  checkGhAuth,
  createPR,
} from "../lib/github.js";
import { detectSentinel, runSentinel } from "../lib/sentinel.js";
import type { SentinelResult } from "../lib/types.js";

interface PrOptions {
  branch: string;
  title?: string;
  dryRun: boolean;
  bodyTemplate?: string;
}

function getCommitList(branch: string): string {
  try {
    const raw = exec(`git log main..${branch} --oneline`, {
      stdio: ["pipe", "pipe", "pipe"],
    });
    return raw
      .trim()
      .split("\n")
      .filter((l) => l.trim())
      .map((l) => `- ${l}`)
      .join("\n");
  } catch {
    return "- No commits found";
  }
}

function getDiffStats(branch: string): string {
  try {
    return exec(`git diff main..${branch} --stat`, {
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
  } catch {
    return "No diff available";
  }
}

function buildSentinelBadge(sentinel: SentinelResult): string {
  if (sentinel.score === null) {
    return "\uD83D\uDEE1\uFE0F **Sentinel: not run**";
  }
  if (sentinel.score >= 80 && sentinel.critical === 0) {
    return `\uD83D\uDEE1\uFE0F **Sentinel: \u2705 Clean (${sentinel.score}/100)**`;
  }
  const totalFindings =
    sentinel.critical + sentinel.warning + sentinel.info;
  return `\uD83D\uDEE1\uFE0F **Sentinel: \u26A0\uFE0F ${totalFindings} findings (${sentinel.score}/100)**`;
}

function buildSentinelSummary(sentinel: SentinelResult): string {
  const criticals = sentinel.findings.filter(
    (f) => f.severity === "critical"
  );
  if (criticals.length === 0) return "";
  return criticals.map((f) => `- [${f.code}] ${f.description}`).join("\n");
}

function buildBody(
  template: string,
  commitList: string,
  diffStats: string,
  sentinel: SentinelResult
): string {
  return template
    .replace("{commit_list}", commitList)
    .replace("{diff_stats}", diffStats)
    .replace("{sentinel_badge}", buildSentinelBadge(sentinel))
    .replace("{sentinel_summary}", buildSentinelSummary(sentinel));
}

const DEFAULT_TEMPLATE = `## ClawPR Report

### Changes
{commit_list}

### Diff Summary
{diff_stats}

### Security
{sentinel_badge}
{sentinel_summary}

---
*Generated by [ClawPR](https://github.com/SkunkWorks0x/clawpr) | Security by [ClawStack Sentinel](https://github.com/SkunkWorks0x/clawstack-sentinel)*`;

export function prCommand(repoArg: string, options: PrOptions): void {
  const parts = repoArg.split("/");
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    console.error("Error: Invalid repo format. Use owner/repo");
    process.exit(1);
  }

  const [owner, repo] = parts as [string, string];

  if (!options.branch) {
    console.error("Error: --branch is required");
    process.exit(1);
  }

  // Verify branch exists
  try {
    exec(`git rev-parse --verify ${options.branch}`, {
      stdio: "pipe",
    });
  } catch {
    console.error(
      `Error: Branch '${options.branch}' not found locally. Did you commit and push?`
    );
    process.exit(1);
  }

  checkGhInstalled();
  checkGhAuth();

  const commitList = getCommitList(options.branch);
  const diffStats = getDiffStats(options.branch);

  // Run sentinel on current directory
  let sentinel: SentinelResult = {
    score: null,
    findings: [],
    critical: 0,
    warning: 0,
    info: 0,
  };

  if (detectSentinel()) {
    sentinel = runSentinel(process.cwd());
  } else {
    process.stderr.write(
      "Warning: Sentinel not found, skipping security scan\n"
    );
  }

  // Build body
  let template = DEFAULT_TEMPLATE;
  if (options.bodyTemplate) {
    try {
      template = readFileSync(options.bodyTemplate, "utf-8");
    } catch {
      console.error(`Error: Template file not found: ${options.bodyTemplate}`);
      process.exit(1);
    }
  }

  const body = buildBody(template, commitList, diffStats, sentinel);
  const title = options.title ?? `ClawPR: Fixes for ${repo}`;

  if (options.dryRun) {
    console.log(body);
    return;
  }

  const prUrl = createPR(owner, repo, options.branch, title, body);
  console.log(prUrl);
}
